apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: ghs
spec:
  type: ClusterIP
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
