apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: ghs

  annotations:
    cloud.google.com/backend-config: '{"default":"auth-backend-config"}'

spec:
  type: ClusterIP

  selector:
    app: auth-service

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
